language: go

go:
  - "1.10"

install: true

#dont email me i dont like spam
notifications:
  email: false

before_script:
  - go get github.com/rwcarlsen/goexif/exif
  - go get github.com/anthonynsimon/bild/imgio
  - go get github.com/anthonynsimon/bild/transform
  - go get golang.org/x/image/tiff
  - go get github.com/bcampbell/fuzzytime
  - go get github.com/oliamb/cutter
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck

script:
  - golint ./ts* -set_exit_status
  - megacheck ./ts*
  - ./build.sh ./tsalign
  - ./build.sh ./tsarchive
  - ./build.sh ./tscrop
  - ./build.sh ./tsorganize
  - ./build.sh ./tsrename
  - ./build.sh ./tsresize
  - ./build.sh ./tsselect

before_deploy:
  - tar -zcvf windows.tar.gz **/*_win*
  - tar -zcvf darwin.tar.gz **/*_darwin*
  - tar -zcvf linux.tar.gz **/*_linux*

deploy:
  provider: releases
  api_key: $TOKEN
  file_glob: true
  file:
    - "windows.tar.gz"
    - "darwin.tar.gz"
    - "linux.tar.gz"
  name: Release $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
