language: go

go:
  - "1.X"

install: true

#dont email me i dont like spam
notifications:
  email: false

#before_script:
#  - go get

script: ./build.sh

  - provider: releases
    api_key: $TOKEN
    file: *_win*
    name: Build $(date +'%d.%m.%Y %R') - WIN
    skip_cleanup: true

  - provider: releases
    api_key: $TOKEN
    file: *_linux*
    name: Build $(date +'%d.%m.%Y %R') - LINUX
    skip_cleanup: true

  - provider: releases
    api_key: $TOKEN
    file: *_darwin*
    name: Build $(date +'%d.%m.%Y %R') - DARWIN
    skip_cleanup: true
